name: CI/CD PIPELINE FOR PULL REQUESTS ON HAUSAFLIX

on:
  pull_request:
    branches:
      - main

jobs:
    build: 
        runs-on: ubuntu-latest

        steps:

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'

            - name: # Install application dependencies using `npm install or yarn install`
              run: yarn install
            
            - name: Build the application (if needed)
              run: yarn build

            - name: Run the application
              run: yarn start

              
